version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    ports:
      - "9000:9000" # optional: expose PHP-FPM if needed

  node:
    command: npm run dev
    ports:
      - "3000:3000" # Vite dev server port
    volumes:
      - ./:/var/www
      - /var/www/node_modules

  nginx:
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
