version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: portfolio-app
    container_name: portfolio-app
    restart: unless-stopped
    working_dir: /var/www
    # No volume mounts in production
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    ports:
      - "9000:9000" # optional: expose PHP-FPM if needed
    networks:
      - app-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        MODE: production
    image: portfolio-node
    container_name: portfolio-node
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "3000:3000" # Vite dev server port
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: portfolio-nginx
    container_name: portfolio-nginx
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
